version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  golang:
    # image: golang:1.16
    build:
      context: ./
    container_name: golang-app-container
    ports:
      - "8080:8080"
      # depends_on:
      # - postgres


volumes:
  postgres-data:
