// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: seller.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCoupon = `-- name: DeleteCoupon :exec

DELETE FROM "coupon" c
WHERE c."id" = $2 AND "shop_id" = (
        SELECT s."id"
        FROM "shop" s
        WHERE
            s."seller_name" = $1
            AND s."enabled" = true
    )
`

type DeleteCouponParams struct {
	SellerName string `json:"seller_name" params:"seller_name"`
	ID         int32  `json:"id" params:"id"`
}

func (q *Queries) DeleteCoupon(ctx context.Context, arg DeleteCouponParams) error {
	_, err := q.db.Exec(ctx, deleteCoupon, arg.SellerName, arg.ID)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec

UPDATE "product" p
SET
    "enabled" = false,
    "edit_date" = NOW()
WHERE "shop_id" = (
        SELECT s."id"
        FROM "shop" s
        WHERE
            s."seller_name" = $1
            AND s."enabled" = true
    )
    AND p."id" = $2
`

type DeleteProductParams struct {
	SellerName string `json:"seller_name" params:"seller_name"`
	ID         int32  `json:"id" params:"id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.Exec(ctx, deleteProduct, arg.SellerName, arg.ID)
	return err
}

const getSellerInfo = `-- name: GetSellerInfo :one

SELECT s.id, s.seller_name, s.image_id, s.name, s.description, s.enabled
FROM "user" u
    JOIN "shop" s ON u.username = s.seller_name
WHERE u.id = $1
`

func (q *Queries) GetSellerInfo(ctx context.Context, id int32) (Shop, error) {
	row := q.db.QueryRow(ctx, getSellerInfo, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.SellerName,
		&i.ImageID,
		&i.Name,
		&i.Description,
		&i.Enabled,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :one

INSERT INTO
    "tag" ("shop_id", "name")
VALUES ( (
            SELECT s."id"
            FROM "shop" s
            WHERE
                s."seller_name" = $1
                AND s."enabled" = true
        ),
        $2
    ) RETURNING ("id", "name")
`

type InsertTagParams struct {
	SellerName string `json:"seller_name" params:"seller_name"`
	Name       string `json:"name"`
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, insertTag, arg.SellerName, arg.Name)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const searchTag = `-- name: SearchTag :many

SELECT t."id", t."name"
FROM "tag" t
    JOIN "shop" s ON "shop_id" = s.id
    JOIN "user" u ON s.seller_name = u.username
WHERE u.id = $1 AND t."name" ~* $2
ORDER BY LENGTH(t."name")
LIMIT 10
`

type SearchTagParams struct {
	ID   int32  `json:"id" params:"id"`
	Name string `json:"name"`
}

type SearchTagRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) SearchTag(ctx context.Context, arg SearchTagParams) ([]SearchTagRow, error) {
	rows, err := q.db.Query(ctx, searchTag, arg.ID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTagRow
	for rows.Next() {
		var i SearchTagRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sellerGetCoupon = `-- name: SellerGetCoupon :many

SELECT
    c."id",
    c."type",
    c."shop_id",
    c."name",
    c."discount",
    c."expire_date"
FROM "coupon" c
    JOIN "shop" s ON c."shop_id" = s.id
WHERE s.seller_name = $1
ORDER BY "start_date" DESC
LIMIT $2
OFFSET $3
`

type SellerGetCouponParams struct {
	SellerName string `json:"seller_name" params:"seller_name"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

type SellerGetCouponRow struct {
	ID         int32              `json:"id" params:"id"`
	Type       CouponType         `json:"type"`
	ShopID     int32              `json:"shop_id"`
	Name       string             `json:"name"`
	Discount   pgtype.Numeric     `json:"discount"`
	ExpireDate pgtype.Timestamptz `json:"expire_date"`
}

func (q *Queries) SellerGetCoupon(ctx context.Context, arg SellerGetCouponParams) ([]SellerGetCouponRow, error) {
	rows, err := q.db.Query(ctx, sellerGetCoupon, arg.SellerName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerGetCouponRow
	for rows.Next() {
		var i SellerGetCouponRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ShopID,
			&i.Name,
			&i.Discount,
			&i.ExpireDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sellerGetCouponDetail = `-- name: SellerGetCouponDetail :one

SELECT c.id, c.type, c.shop_id, c.name, c.description, c.discount, c.start_date, c.expire_date
FROM "coupon" c
    JOIN "shop" s ON c."shop_id" = s.id
WHERE
    s."seller_name" = $1
    AND c."id" = $2
`

type SellerGetCouponDetailParams struct {
	SellerName string `json:"seller_name" params:"seller_name"`
	ID         int32  `json:"id" params:"id"`
}

func (q *Queries) SellerGetCouponDetail(ctx context.Context, arg SellerGetCouponDetailParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, sellerGetCouponDetail, arg.SellerName, arg.ID)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.Discount,
		&i.StartDate,
		&i.ExpireDate,
	)
	return i, err
}

const sellerGetOrder = `-- name: SellerGetOrder :many

SELECT
    "id",
    "shop_id",
    "shipment",
    "total_price",
    "status",
    "created_at"
FROM "order_history"
WHERE "shop_id" = (
        SELECT s."id"
        FROM "shop" s
        WHERE
            s."seller_name" = $1
            AND s."enabled" = true
    )
ORDER BY "created_at" DESC
LIMIT $2
OFFSET $3
`

type SellerGetOrderParams struct {
	SellerName string `json:"seller_name" params:"seller_name"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

type SellerGetOrderRow struct {
	ID         int32              `json:"id"`
	ShopID     int32              `json:"shop_id"`
	Shipment   int32              `json:"shipment"`
	TotalPrice int32              `json:"total_price"`
	Status     OrderStatus        `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SellerGetOrder(ctx context.Context, arg SellerGetOrderParams) ([]SellerGetOrderRow, error) {
	rows, err := q.db.Query(ctx, sellerGetOrder, arg.SellerName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerGetOrderRow
	for rows.Next() {
		var i SellerGetOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Shipment,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sellerGetOrderDetail = `-- name: SellerGetOrderDetail :one

SELECT order_id, product_id, product_version, quantity, product_archive.id, product_archive.version, product_archive.name, product_archive.description, product_archive.price, product_archive.image_id, product.id, product.version, shop_id, product.name, product.description, product.price, product.image_id, exp_date, edit_date, stock, sales, product.enabled, shop.id, seller_name, shop.image_id, shop.name, shop.description, shop.enabled
FROM "order_detail"
    JOIN "product_archive" ON "order_detail"."product_id" = "product"."id" AND "order_detail"."version" = "product"."version"
    JOIN "product" ON "order_detail"."product_id" = "product"."id"
    JOIN "shop" ON "product"."shop_id" = "shop"."id"
WHERE
    "shop"."seller_name" = $1
    AND "order_id" = $2
`

type SellerGetOrderDetailParams struct {
	SellerName string `json:"seller_name" params:"seller_name"`
	OrderID    int32  `json:"order_id"`
}

type SellerGetOrderDetailRow struct {
	OrderID        int32              `json:"order_id"`
	ProductID      int32              `json:"product_id"`
	ProductVersion int32              `json:"product_version"`
	Quantity       int32              `json:"quantity"`
	ID             int32              `json:"id"`
	Version        int32              `json:"version"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	Price          pgtype.Numeric     `json:"price"`
	ImageID        pgtype.UUID        `json:"image_id"`
	ID_2           int32              `json:"id_2" params:"id"`
	Version_2      int32              `json:"version_2"`
	ShopID         int32              `json:"shop_id"`
	Name_2         string             `json:"name_2"`
	Description_2  string             `json:"description_2"`
	Price_2        pgtype.Numeric     `json:"price_2"`
	ImageID_2      pgtype.UUID        `json:"image_id_2"`
	ExpDate        pgtype.Timestamptz `json:"exp_date"`
	EditDate       pgtype.Timestamptz `json:"edit_date"`
	Stock          int32              `json:"stock"`
	Sales          int32              `json:"sales"`
	Enabled        bool               `json:"enabled"`
	ID_3           int32              `json:"id_3"`
	SellerName     string             `json:"seller_name" params:"seller_name"`
	ImageID_3      pgtype.UUID        `json:"image_id_3"`
	Name_3         string             `json:"name_3"`
	Description_3  string             `json:"description_3"`
	Enabled_2      bool               `json:"enabled_2"`
}

func (q *Queries) SellerGetOrderDetail(ctx context.Context, arg SellerGetOrderDetailParams) (SellerGetOrderDetailRow, error) {
	row := q.db.QueryRow(ctx, sellerGetOrderDetail, arg.SellerName, arg.OrderID)
	var i SellerGetOrderDetailRow
	err := row.Scan(
		&i.OrderID,
		&i.ProductID,
		&i.ProductVersion,
		&i.Quantity,
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.ImageID,
		&i.ID_2,
		&i.Version_2,
		&i.ShopID,
		&i.Name_2,
		&i.Description_2,
		&i.Price_2,
		&i.ImageID_2,
		&i.ExpDate,
		&i.EditDate,
		&i.Stock,
		&i.Sales,
		&i.Enabled,
		&i.ID_3,
		&i.SellerName,
		&i.ImageID_3,
		&i.Name_3,
		&i.Description_3,
		&i.Enabled_2,
	)
	return i, err
}

const sellerInsertCoupon = `-- name: SellerInsertCoupon :one

INSERT INTO
    "coupon" (
        "type",
        "shop_id",
        "description",
        "discount",
        "start_date",
        "expire_date"
    )
VALUES (
        $2, (
            SELECT s."id"
            FROM "shop" s
            WHERE
                s."seller_name" = $1
                AND s."enabled" = true
        ),
        $3,
        $4,
        $5,
        $6
    ) RETURNING id, type, shop_id, name, description, discount, start_date, expire_date
`

type SellerInsertCouponParams struct {
	SellerName  string             `json:"seller_name" params:"seller_name"`
	Type        CouponType         `json:"type"`
	Description string             `json:"description"`
	Discount    pgtype.Numeric     `json:"discount"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	ExpireDate  pgtype.Timestamptz `json:"expire_date"`
}

func (q *Queries) SellerInsertCoupon(ctx context.Context, arg SellerInsertCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, sellerInsertCoupon,
		arg.SellerName,
		arg.Type,
		arg.Description,
		arg.Discount,
		arg.StartDate,
		arg.ExpireDate,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.Discount,
		&i.StartDate,
		&i.ExpireDate,
	)
	return i, err
}

const sellerInsertProduct = `-- name: SellerInsertProduct :one



INSERT INTO
    "product"(
        "version",
        "shop_id",
        "name",
        "description",
        "price",
        "image_id",
        "exp_date"
    )
VALUES (
        0, (
            SELECT s."id"
            FROM "shop" s
            WHERE
                s."seller_name" = $1
                AND s."enabled" = true
        ),
        $2,
        $3,
        $4,
        $5,
        $6
    ) RETURNING "id"
`

type SellerInsertProductParams struct {
	SellerName  string             `json:"seller_name" params:"seller_name"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	ImageID     pgtype.UUID        `json:"image_id"`
	ExpDate     pgtype.Timestamptz `json:"exp_date"`
}

// SellerGetReport :many
// SellerGetReportDetail :many
func (q *Queries) SellerInsertProduct(ctx context.Context, arg SellerInsertProductParams) (int32, error) {
	row := q.db.QueryRow(ctx, sellerInsertProduct,
		arg.SellerName,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.ImageID,
		arg.ExpDate,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateCouponInfo = `-- name: UpdateCouponInfo :exec

UPDATE "coupon" c
SET
    "type" = COALESCE($3, "type"),
    "description" = COALESCE($4, "description"),
    "discount" = COALESCE($5, "discount"),
    "start_date" = COALESCE($6, "start_date"),
    "expire_date" = COALESCE($7, "expire_date")
WHERE c."id" = $2 AND "shop_id" = (
        SELECT s."id"
        FROM "shop" s
        WHERE
            s."seller_name" = $1
            AND s."enabled" = true
    )
`

type UpdateCouponInfoParams struct {
	SellerName  string             `json:"seller_name" params:"seller_name"`
	ID          int32              `json:"id" params:"id"`
	Type        CouponType         `json:"type"`
	Description string             `json:"description"`
	Discount    pgtype.Numeric     `json:"discount"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	ExpireDate  pgtype.Timestamptz `json:"expire_date"`
}

func (q *Queries) UpdateCouponInfo(ctx context.Context, arg UpdateCouponInfoParams) error {
	_, err := q.db.Exec(ctx, updateCouponInfo,
		arg.SellerName,
		arg.ID,
		arg.Type,
		arg.Description,
		arg.Discount,
		arg.StartDate,
		arg.ExpireDate,
	)
	return err
}

const updateProductInfo = `-- name: UpdateProductInfo :exec

UPDATE "product" p
SET
    "name" = COALESCE($3, "name"),
    "description" = COALESCE($4, "description"),
    "price" = COALESCE($5, "price"),
    "image_id" = COALESCE($6, "image_id"),
    "exp_date" = COALESCE($7, "exp_date"),
    "edit_date" = NOW(),
    "version" = "version" + 1
WHERE "shop_id" = (
        SELECT s."id"
        FROM "shop" s
        WHERE
            s."seller_name" = $1
            AND s."enabled" = true
    )
    AND p."id" = $2
`

type UpdateProductInfoParams struct {
	SellerName  string             `json:"seller_name" params:"seller_name"`
	ID          int32              `json:"id" params:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	ImageID     pgtype.UUID        `json:"image_id"`
	ExpDate     pgtype.Timestamptz `json:"exp_date"`
}

func (q *Queries) UpdateProductInfo(ctx context.Context, arg UpdateProductInfoParams) error {
	_, err := q.db.Exec(ctx, updateProductInfo,
		arg.SellerName,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.ImageID,
		arg.ExpDate,
	)
	return err
}

const updateSellerInfo = `-- name: UpdateSellerInfo :exec

UPDATE "shop"
SET
    "image_id" = COALESCE($2, "image_id"),
    "name" = COALESCE($3, "name"),
    "description" = COALESCE($4, "description"),
    "enabled" = COALESCE($5, "enabled")
WHERE "seller_name" IN (
        SELECT "username"
        FROM "user" u
        WHERE u.id = $1
    )
`

type UpdateSellerInfoParams struct {
	ID          int32       `json:"id" params:"id"`
	ImageID     pgtype.UUID `json:"image_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Enabled     bool        `json:"enabled"`
}

func (q *Queries) UpdateSellerInfo(ctx context.Context, arg UpdateSellerInfoParams) error {
	_, err := q.db.Exec(ctx, updateSellerInfo,
		arg.ID,
		arg.ImageID,
		arg.Name,
		arg.Description,
		arg.Enabled,
	)
	return err
}
