// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: user.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUser = `-- name: AddUser :exec

INSERT INTO
    "user" (
        "username",
        "password",
        "name",
        "email",
        "address",
        "image_id",
        "role",
        "credit_card"
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        '',
        $5,
        'customer',
        '{}'
    )
`

type AddUserParams struct {
	Username string      `json:"username"`
	Password string      `json:"password"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	ImageID  pgtype.UUID `json:"image_id" swaggertype:"string"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.Exec(ctx, addUser,
		arg.Username,
		arg.Password,
		arg.Name,
		arg.Email,
		arg.ImageID,
	)
	return err
}

const userExists = `-- name: UserExists :one

SELECT EXISTS (
        SELECT 1
        FROM "user"
        WHERE
            "username" = $1
            OR "email" = $2
    )
`

type UserExistsParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) UserExists(ctx context.Context, arg UserExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, arg.Username, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userGetCreditCard = `-- name: UserGetCreditCard :one

SELECT "credit_card" FROM "user" WHERE "id" = $1
`

func (q *Queries) UserGetCreditCard(ctx context.Context, id int32) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, userGetCreditCard, id)
	var credit_card json.RawMessage
	err := row.Scan(&credit_card)
	return credit_card, err
}

const userGetInfo = `-- name: UserGetInfo :one

SELECT
    "id",
    "name",
    "email",
    "image_id",
    "enabled"
FROM "user" u
WHERE u.id = $1
`

type UserGetInfoRow struct {
	ID      int32       `json:"id" param:"id"`
	Name    string      `json:"name"`
	Email   string      `json:"email"`
	ImageID pgtype.UUID `json:"image_id" swaggertype:"string"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) UserGetInfo(ctx context.Context, id int32) (UserGetInfoRow, error) {
	row := q.db.QueryRow(ctx, userGetInfo, id)
	var i UserGetInfoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ImageID,
		&i.Enabled,
	)
	return i, err
}

const userUpdateCreditCard = `-- name: UserUpdateCreditCard :one

UPDATE "user"
SET "credit_card" = $2
WHERE
    "id" = $1 RETURNING "credit_card"
`

type UserUpdateCreditCardParams struct {
	ID         int32           `json:"id" param:"id"`
	CreditCard json.RawMessage `json:"credit_card"`
}

func (q *Queries) UserUpdateCreditCard(ctx context.Context, arg UserUpdateCreditCardParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, userUpdateCreditCard, arg.ID, arg.CreditCard)
	var credit_card json.RawMessage
	err := row.Scan(&credit_card)
	return credit_card, err
}

const userUpdateInfo = `-- name: UserUpdateInfo :one

UPDATE "user"
SET
    "name" = COALESCE($2, "name"),
    "email" = COALESCE($3, "email"),
    "address" = COALESCE($4, "address"),
    "image_id" = COALESCE($5, "image_id")
WHERE
    "id" = $1 RETURNING "id",
    "name",
    "email",
    "image_id",
    "enabled"
`

type UserUpdateInfoParams struct {
	ID      int32       `json:"id" param:"id"`
	Name    string      `json:"name"`
	Email   string      `json:"email"`
	Address string      `json:"address"`
	ImageID pgtype.UUID `json:"image_id" swaggertype:"string"`
}

type UserUpdateInfoRow struct {
	ID      int32       `json:"id" param:"id"`
	Name    string      `json:"name"`
	Email   string      `json:"email"`
	ImageID pgtype.UUID `json:"image_id" swaggertype:"string"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) UserUpdateInfo(ctx context.Context, arg UserUpdateInfoParams) (UserUpdateInfoRow, error) {
	row := q.db.QueryRow(ctx, userUpdateInfo,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Address,
		arg.ImageID,
	)
	var i UserUpdateInfoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ImageID,
		&i.Enabled,
	)
	return i, err
}

const userUpdatePassword = `-- name: UserUpdatePassword :one

UPDATE "user"
SET
    "password" = $2
WHERE
    "id" = $1
    AND "password" = $3 RETURNING "id",
    "name",
    "email",
    "address",
    "image_id",
    "enabled"
`

type UserUpdatePasswordParams struct {
	ID              int32  `json:"id" param:"id"`
	NewPassword     string `json:"new_password"`
	CurrentPassword string `json:"current_password"`
}

type UserUpdatePasswordRow struct {
	ID      int32       `json:"id" param:"id"`
	Name    string      `json:"name"`
	Email   string      `json:"email"`
	Address string      `json:"address"`
	ImageID pgtype.UUID `json:"image_id" swaggertype:"string"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) UserUpdatePassword(ctx context.Context, arg UserUpdatePasswordParams) (UserUpdatePasswordRow, error) {
	row := q.db.QueryRow(ctx, userUpdatePassword, arg.ID, arg.NewPassword, arg.CurrentPassword)
	var i UserUpdatePasswordRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Address,
		&i.ImageID,
		&i.Enabled,
	)
	return i, err
}
